apiVersion: v1
kind: ResourceQuota
metadata:
  name: quota-1
  namespace: argoapp1
spec:
  hard:
    requests.ephemeral-storage: '25G'
    limits.ephemeral-storage: '25G'
    services.loadbalancers: "12",
    services.nodeports: "0"
