apiVersion: v1
kind: Service
metadata:
  name: test-mlb
spec:
  selector:
    app.kubernetes.io/instance: cnfm-stc-lab
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  type: LoadBalancer
